# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Smugglex < Formula
  desc "Rust-powered http smuggling scanner"
  homepage "https://github.com/hahwul/smugglex"
  url "https://github.com/hahwul/smugglex/archive/refs/tags/0.1.0.tar.gz"
  sha256 "81f4f85c4ce97784c854d9f2e9e3dde647346aa2ef7adc9b5a255cfb1b1be286"
  license "MIT"

  depends_on "rust"

  def install
    system "cargo build --release"
bin.install "target/release/smugglex"
  end

  test do
    system "{bin}/smugglex", "-V"
  end
end
